### ISSUE TITLE
After updating to 3.1.0: java.lang.NoClassDefFoundError: com/arangodb/velocypack/VPackModule

### ISSUE THREAD

**Issue by jebbench** [arangodb/jackson-dataformat-velocypack#17]
After updating from version 3.0.1 to 3.1.0 I get an exception when calling `ArangoDBAsync.Builder()`.

```
java.lang.NoClassDefFoundError: com/arangodb/velocypack/VPackModule
```

Gradle dependancies are:
```
    implementation 'com.arangodb:arangodb-java-driver:6.20.0'
    implementation 'com.arangodb:jackson-dataformat-velocypack:3.1.0'
```

**Comment by rashtao** [comment]
Related to https://github.com/arangodb/arangodb/issues/17840, it happens because both libraries have transitive dependency on `com.arangodb:velocypack`, but `arangodb-java-driver:6.20.0`  requires it to be at version `2.5.x`.

On the other side, `jackson-dataformat-velocypack:3.1.0` transitively includes `com.arangodb:velocypack:3.0.0`, but it can also work with `com.arangodb:velocypack:2.5.x`.

You can work around it by excluding the transitive dependency on `com.arangodb:velocypack` from `jackson-dataformat-velocypack` or forcing specific version of `com.arangodb:velocypack:2.5.x`.

To mitigate this, I will set `com.arangodb:velocypack` as provided dependency in the next release.

**Comment by rashtao** [comment]
To avoid compatibility problems of transitive dependencies, I set the dependency on `com.arangodb:velocypack` as `provided` and released it in https://github.com/arangodb/jackson-dataformat-velocypack/releases/tag/v4.0.0.
